set(_CATKIN_CURRENT_PACKAGE "velocity_control")
set(velocity_control_VERSION "0.0.0")
set(velocity_control_MAINTAINER "Tobias <tobias.tuylu@gmail.com>")
set(velocity_control_PACKAGE_FORMAT "1")
set(velocity_control_BUILD_DEPENDS "dynamic_reconfigure" "geometry_msgs" "roscpp" "rospy" "std_msgs" "nav_msgs" "tf2")
set(velocity_control_BUILD_EXPORT_DEPENDS "dynamic_reconfigure" "geometry_msgs" "roscpp" "rospy" "std_msgs" "nav_msgs" "tf2")
set(velocity_control_BUILDTOOL_DEPENDS "catkin" "catkin")
set(velocity_control_BUILDTOOL_EXPORT_DEPENDS )
set(velocity_control_EXEC_DEPENDS "dynamic_reconfigure" "geometry_msgs" "roscpp" "rospy" "std_msgs" "nav_msgs" "tf2")
set(velocity_control_RUN_DEPENDS "dynamic_reconfigure" "geometry_msgs" "roscpp" "rospy" "std_msgs" "nav_msgs" "tf2")
set(velocity_control_TEST_DEPENDS )
set(velocity_control_DOC_DEPENDS )
set(velocity_control_DEPRECATED "")